create table users
(
    id         int8 generated by default as identity,
    username   varchar(255) /*not null*/,
    name       varchar(255) /*not null*/,
    email      varchar(255) /*not null*/,
    birth_date date /*not null*/,
    sex        varchar(10) /*not null*/
);

comment on table users is 'Таблица для хранения информации о пользователе';

alter table users
    add constraint user_pk
        primary key (id);

create unique index user_id_uindex
    on users (id);

-- create unique index user_username_uindex
--     on users (username);
