create table photo
(
    id    int8 generated by default as identity,
    name  varchar(255) /*not null*/,
    type  varchar(255) /*not null*/,
    bytes bytea /*not null*/
);

comment on table photo is 'Таблица для хранения фоторафий';

alter table photo
    add constraint photo_pk
        primary key (id);

create unique index photo_id_uindex
    on photo (id);

alter table "user"
    add photo_id int8;

alter table "user"
    add constraint user_photo_id_fk
        foreign key (photo_id) references photo;
